//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSLS.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int Id { get; set; }
        public System.DateTime BorrowTime { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public System.DateTime DateShouldBeReturn { get; set; }
        public Nullable<int> WhetherToRenew { get; set; }
        public int ReaderId { get; set; }
        public int BookId { get; set; }
        public Nullable<int> FineId { get; set; }
        public Nullable<int> Overdays { get; set; }
        public string NeedtoFine { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Fine Fine { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
